name: alfa_citizen
description: Location-aware citizen safety app with on-device AI modules.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  geolocator: ^13.0.2
  http: ^1.2.2
  image: ^4.2.0
  image_picker: ^1.1.2
  shared_preferences: ^2.3.5
  tflite_flutter: ^0.12.1
  url_launcher: ^6.3.1
  firebase_core: ^4.11.0
  cloud_firestore: ^6.6.0
  video_player: ^2.11.1
  flutter_vlc_player: ^7.4.3
  crypto: ^3.0.6
  sqflite: ^2.4.3
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  sqflite_common_ffi: ^2.4.2

flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/videos/
    - assets/icons/
